import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import svgr from "vite-plugin-svgr";
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { safelist } from './src/stylesets/index';

function safelistPlugin() {
  return {
    name: 'vite-plugin-safelist',
    buildStart() {
      const outPath = resolve(__dirname, 'src/stylesets/index.txt');
      writeFileSync(outPath, safelist.join('\n'), 'utf-8');
      console.log('✅ Safelist generated by Vite plugin');
    }
  };
}

// https://vite.dev/config/
export default defineConfig({
    plugins: [svgr(), react(), safelistPlugin(), tailwindcss()],
    base: '/FM-CSS-4'
})

